# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas = [
    ('main.db', '.'),
    ('main.html', '.'),
    ('filter.html', '.'),
    ('original.html', '.'),
    ('static/images/layers.png', '.'),
    ('static/images/layers-2x.png', '.'),
    ('static/images/marker-icon.png', '.'),
    ('static/images/marker-icon-2x.png', '.'),
    ('static/images/marker-shadow.png', '.'),
    ('static/images/spritesheet.png', '.'),
    ('static/images/spritesheet.svg', '.'),
    ('static/images/spritesheet-2x.png', '.'),
    ('static/all.min.css', '.'),
    ('static/bootstrap.min.css', '.'),
    ('static/bootstrap.bundle.min.js', '.'),
    ('static/jquery-3.7.1.min.js', '.'),
    ('static/leaflet.awesome.rotate.min.css', '.'),
    ('static/leaflet.awesome-markers.css', '.'),
    ('static/leaflet.awesome-markers.js', '.'),
    ('static/leaflet.css', '.'),
    ('static/leaflet.draw.css', '.'),
    ('static/leaflet.draw.js', '.'),
    ('static/main.js', '.'),
],
    hiddenimports=['fastapi', 'fiona._shim', 'dotenv'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
